blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/FelipePaterni/reseller/blob/main/README.md
    about: Check the project documentation
  - name: 💬 Discussions
    url: https://github.com/FelipePaterni/reseller/discussions
    about: Ask questions and discuss ideas with the community
